services:
  xtts:
    image: ghcr.io/coqui-ai/xtts-streaming-server:latest-cuda121
    container_name: xtts
    ports:
      - "8881:80"
    environment:
      COQUI_TOS_AGREED: "1"
    gpus: all
    restart: unless-stopped